subroutine triangle_read_mesh ( file_name, Mesh )
!!$ ***********************************************************************
!!$ Author :: Wenju Zhao
!!$ Email :: zwenju@outlook.com
!!$ Read the mesh information generated by the triangle software
!!$ ***********************************************************************  
  use Mesh_Type_H
  implicit none
  type (mesh_type),intent(inout) :: Mesh 
  character(len=*),intent(in)  :: file_name 
  character(len=200) :: node_file, element_file 
  integer(kind=4)::iNode, iElement   
  integer(kind=4):: i, NULL 


  node_file     =  trim(file_name)//'.node'
  element_file  =  trim(file_name)//'.ele'

  !!
  !! read node file 
  !!
  open(1,file=node_file, action = 'read')
  read(1,*) Mesh%NodeNum, NULL, NULL, NULL 

  allocate(Mesh%NodeList(2, Mesh%NodeNum))
  allocate(Mesh%NodeBdryList(Mesh%NodeNum))
  !!
  !! read each line of node file 
  !!
  NodeList_loop : do iNode = 1, Mesh%NodeNum
     read(1,*) NULL, (Mesh%NodeList(i,iNode), i = 1, 2), Mesh%NodeBdryList(iNode)
  enddo NodeList_loop

  close(1)

  !!
  !! read element file 
  !!
  open(1,file=element_file, action = 'read')
  read(1,*) Mesh%ElementNum, NULL, NULL 
  allocate(Mesh%ElementList(6,Mesh%ElementNum))
  !!
  !! read each line of element file 
  !!
  ElementList_loop : do iElement = 1, Mesh%ElementNum 
     read(1,*) Null, (Mesh%ElementList(i,iElement), i = 1, 6)
  enddo ElementList_loop

  close(1)

  !!
  !!  compuate the vertex num and system dimension
  !!
  Mesh%VertexNum = (1 + Mesh%NodeNum - ( Mesh%ElementNum + Mesh%RegionHolesNum )) / 2 
  !!
  !! this is intended to compute the dimension of the global system 
  !!
  !! Mesh%DimNum = Mesh%RegionDimension * Mesh%NodeNum + Mesh%VertexNum 
  !!
  return 
end subroutine triangle_read_mesh


