subroutine triangle_save_mesh_py (mesh, file_name)
!!$ ******************************************************************************
!!$ Author:: Wenju zhao
!!$ Email :: zwenju@outlook.com
!!$ Purpose :
!!$ this routine outputs the element and node list into files *.ele, *.node
!!$ the output formats are same as the triangle ()
!!$ the mesh can be plot using (showme   meshfile)
!!$ for examples, refer to Generated by triangle -po2 A.poly
!!$ ******************************************************************************  
  use Mesh_Type_H
  implicit none
  type (mesh_type) :: Mesh 
  character(len=*) :: file_name 
  character(len=200) :: element_file, node_file 
  integer(kind=4), parameter :: out_unit = 1111111
  integer(kind=4) :: iElement, iNode 


  element_file = trim(file_name)//'.ele'
  node_file    = trim(file_name)//'.node'

  !!
  !! write the element list into file
  !!
  open (unit = out_unit, file = element_file, action = "write") 
  !!
  !! First line: <# of triangles> <nodes per triangle> <# of attributes> 
  !!
  !! write (out_unit, *) Mesh%ElementNum, 6, 0
  
  do iElement  = 1, Mesh%ElementNum 
     !!
     !! Remaining lines: <triangle #> <node> <node> <node> ... [attributes] 
     !!
     write (out_unit, *) iElement, Mesh%ElementList(1:6, iElement) 
  enddo

  close (out_unit)



  !!
  !! write the node list into file 
  !!
  open (unit = out_unit, file = node_file, action = "write") 
  !!
  !! First line: <# of vertices> <dimension (must be 2)> <# of attributes> <# of boundary markers (0 or 1)> 
  !!
  !! write (out_unit, *) Mesh%NodeNum, 2, 0, 1
  
  do iNode =  1, Mesh%NodeNum 
     !!
     !!Remaining lines: <vertex #> <x> <y> [attributes] [boundary marker] 
     !!
     write (out_unit, *) iNode,  Mesh%NodeList(1:2, iNode), Mesh%NodeBdryList(iNode) 
  enddo

  close (out_unit)


return 
end subroutine triangle_save_mesh_py 
